### ISSUE TITLE
Hook: Maxwell global marsh synthesis

### ISSUE THREAD

**Issue by jaxinewolfe** [Smithsonian/CCN-Data-Library#106]
Bringing in data from [Maxwell et al 2023](https://www.nature.com/articles/s41597-023-02633-x)

**Comment by jaxinewolfe** [comment]
- The methods and bibliography need constructing
- There are 1300+ cores where there is only a single depth interval observation (mostly surface sampling)
- Described treatments/impacts: "Post-fires, input of black carbon", "Grazed", "Ungrazed", "Control", "Historic-Breach", "Natural", "Managed Realignment", "Invaded", "Uninvaded"

**Comment by HolmquistJ** [comment]
I say no on a cutoff for surface samples. Let's go ahead and include them.

**Comment by HolmquistJ** [comment]
@jaxinewolfe Don't worry about recreating the methods table if Tania did not code this. We haven't gone back and done this for the other syntheses. Focus on making sure all of the bibliography data gets represented well and moving this one forward.

**Comment by jaxinewolfe** [comment]
The Maxwell cites a different repository for Lisa and Pat's Abu Dhabi dataset:
https://datadryad.org/stash/dataset/doi:10.15146/R3K59Z

Need to compare the contents with the SI repository version:
https://repository.si.edu/handle/10088/31949
