### ISSUE TITLE
Update attribute names QA test

### ISSUE THREAD

**Issue by mlonneman** [Smithsonian/CCN-Data-Library#35]
Rewrite function to not require including the name of the table as an argument. Join controlled and uncontrolled vocab tables to exclude uncontrolled attributes from violating the test.

**Comment by mlonneman** [comment]
Additionally, change test name to "testAttributeNames" to fit vocabulary used in guidance

**Comment by jaxinewolfe** [comment]
Function has been updated, but it doesn't join controlled and uncontrolled variables. Just controlled for now. Need to reevaluate the uncontrolled vars table. If a variable is uncontrolled and included in the synthesis, it still needs defining for the end user. Need to make sure that transfers to the Atlas data dictionary.
