### ISSUE TITLE
Sanderman synthesis uncited data

### ISSUE THREAD

**Issue by mlonneman** [Smithsonian/CCN-Data-Library#60]
We have permission to include all data contributed to Sanderman synthesis that doesn't have a citation or was contributed via "personal communication". See this issue for more detail: https://github.com/Smithsonian/CCRCN-Data-Library-Map/issues/97

**Comment by jaxinewolfe** [comment]
I added citations for datasets that were previously un-cited (resulting in them being dropped from the Atlas). Now they will be associated with the Sanderman data release. 

Note: A QAQC step should be introduced in the future which checks this at the hook script or synthesis level.
