### ISSUE TITLE
One to one relationship violation between citation and bibliography ID

### ISSUE THREAD

**Issue by mlonneman** [Smithsonian/CCN-Data-Library#64]
The following study IDs have multiple citations associated with a single bibliography ID, however, all the hook scripts will have to be revisited to eliminate the redundant *key* column and standardize assigned publication type. This should be easily fixed in the hook scripts.

- [x] Abbott_et_al_2019	
- [x] Alongi_et_al_2000	
- [ ] Alongi_et_al_2008	
- [x] Belshe_et_al_2019	
- [x] Breithaupt_et_al_2014	
- [x] Callaway_et_al_2019	
- [ ] Doughty_et_al_2016	
- [x] Kauffman_et_al_2020	
- [ ] Kristensen_et_al_2000	
- [x] Lagomasino_et_al_2020	
- [x] Nolte_2020	
- [x] StLaurent_et_al_2020	
- [x] Thom_1992	
- [x] Weis_et_al_2001

**Comment by jaxinewolfe** [comment]
Few notes: 
- My current formula for assigning bibliography_id is paste0('Author_et_al_', year), however, there are cases where the article and data release were published in the same year (i.e. StLaurent). Currently, I add '_data' to the data release bib, but I wonder if we should we have a formula for assigning bibliography_id in every case (ex. appending 'article', 'data', or 'synthesis' to the end).
- For publication type, I've been using the categories: primary, associated, and synthesis (in which primary defaults to the data release). We'll have to come up with official definitions for these categories to be added to the controlled tables.

**Comment by jaxinewolfe** [comment]
RefManageR::GetBibEntryWithDOI() usually works but can be pretty finicky so we should avoid using it more than we have to in hook scripts. Currently, I put an *if statement* around the citation-generating workflow that checks to see if the study citation  table is already present in the derivative folder. Ideally, we should only have to use the function once per hook script.

**Comment by jaxinewolfe** [comment]
We should no longer rely on RefManageR::GetBibEntryWithDOI(). There needs to be a more stable method for cataloguing study citations. Here are three options:
1) download Bibtex article citation(s) to the intermediate data folder, read in to curate and output to final folder
2) create the study citation in the curation script and output it using writeBib(as.BibEntry(study_citation))
3) create a study_citation.csv in the intermediate folder, read it in and output bib file to final folder
