### ISSUE TITLE
Hook Script Reviews

### ISSUE THREAD

**Issue by jaxinewolfe** [Smithsonian/CCN-Data-Library#65]
Revisit all hook scripts in the Data Library. Make sure the scripts run properly, perform QAQC on the data, and update citations (see issue #64). **Please note any problems that arise for particular hook scripts in this issue thread!**

Standard quality checks for each hook script:
- testTableCols(): test that column names in each table match CCRCN guidelines
- testTableVars(): test that variable names in each table match CCRCN guidelines
- testRequired(): checks for the presence of mandatory and conditionally mandatory attributes
- test_unique_cores(): test that all core IDs are unique within the study
- test_unique_coords(): test that all core positions are unique (*Soon to be replaced by checkDuplicates()*)
- test_core_relationships(): test that core IDs in the cores table also exist in the depthseries table (and vice versa)
- fraction_not_percent(): test that attributes are expressed as fractions and not percents (where applicable) 
- test_numeric_vars(): summarize values in numeric columns for the given table (usu. depthseries)

 *Coming soon to a qaqc script near you:*
- checkDuplicates(): check if duplicate cores exist in the database
- checkConditional(): check if conditional variables and attributes exist for applicable attributes 

Please check off the primary studies you revisit so we can keep track of progress and avoid duplication of effort:

- [x] Abbott_2019
- [x] Arriola_2017
- [x] Baustian_et_al_2021
- [x] Belshe_2019
- [x] Boyd_2019
- [x] Breithaupt_2014
- [x] Breithaupt_2020
- [x] Buffington_et_al_2020
- [x] Callaway_2019
- [x] Chambers_et_al_2019
- [x] Craft_2007
- [ ] Craft_unsorted - no hook script
- [ ] Deegan_2012 - no derivative folder
- [x] Doughty_2019
- [x] Drexler_2009
- [x] Drexler_2013
- [x] Drexler_2019
- [x] Elsey-Quirk_et_al_2011 - no hook script
- [x] Ensign_et_al_2020
- [x] Fourqurean_2012
- [x] Gerlach_2017
- [x] Giblin_2018
- [x] Gonneea_2018
- [x] Holmquist_2018
- [x] Johnson_2007
- [ ] Jones_2017 - no derivative folder
- [x] Kauffman_et_al_2020
- [x] Kemp_2020
- [x] Keshta_et_al_2020
- [x] Krauss_2018
- [x] Lagomasino_et_al_2020
- [x] Luk_2020
- [x] McTigue_2020
- [x] Messerschmidt_2020
- [x] Nahlik_Fennessy_2016
- [x] Noe_2016
- [x] Nolte_2020
- [x] Osland_2016
- [x] Peck_2020
- [x] Piazza_2020
- [x] Poppe_2019
- [x] Sanborn_Coxson_2020
- [x] Sanderman_2018
- [x] Schile-Beers_2017
- [x] Smith_2015
- [x] StLaurent_et_al_2020
- [x] Thom_2019
- [x] Thorne_2015_a
- [x] Trettin_2017
- [x] Vaughn_et_al_2020
- [x] Watson_Byrne_2013
- [x] Weis_et_al_2001
- [ ] Yando_2016 - data download script?

**Comment by jaxinewolfe** [comment]
Hook scripts:

- [ ] Baustian et al 2021
- [ ] StLaurent et al 2020

**Comment by jaxinewolfe** [comment]
**Notes:**
- some hook scripts (i.e. Watson Byrne 2013 and Weis et al 2001) have "publication_type: peer reviewed publication" in the methods table and I have removed this since the publication_type now lives in the study citations table and has different controlled variables.
- some file paths needed updating.
- *Vaughn_et_al_2020:* Uncontrolled variable in the cores table: salinity_class = estuarine. "estuarine" exists in the guidance but only "estuarine C-CAP" exists in the controlled variables table. Should we add "estuarine" or just recode as the C-CAP class? Same question for palustrine.
- *Trettin_2017*: NO METHODS
- *Thorne_2015_a*: NO METHODS; Added a missing citation for the associated article.
- *Thom_2019*: Workflow wasn't outputting the cores table for some reason. Core_id PB1 exists in the depthseries table but not the core table. Uncontrolled variable in methods table: coring_method = PVC tube or thin-walled metal tube. Can we recode this to something like "pvc and hammer"? 
- *Smith_et_al_2015:* should we create a citation for the PhD thesis (there's no DOI)?

**Comment by jaxinewolfe** [comment]
Studies with duplicate core_ids: Sanborn_and_Coxson_2020 and Baustian_et_al_2020 share core_ids 398 and 399. Duplicate core_ids within Luk_et_al_2020 which can be distinguished by a & b (the cores were split in half and different methods were used).

**Comment by jaxinewolfe** [comment]
**Attributes**
*Controlled attributes in question:*
- depthseries: marker_age; marker_age_sd; representative_depth_min/max; dating_interval_notes

**Variables**
*The following variables will be defined and added to the controlled variable table:*
- impact_class = salt impacted; natural 
- core_elevation_datum = NAP; NHN
- coring_method = soil pit
- salinity_class = estuarine

*Controlled variables in question:*
- excess_pb210_rate = mass accumulation and accretion
- habitat and vegetation_class are starting to overlap in variables. Should we leave "mudflat" to habitat and classify it as "unvegetated" in vegetation class?

**Comment by HolmquistJ** [comment]
I think that methods_id should only be indexed in the methods and depth interval tables since one core can have more than one set of methods associated with it. For instance, in the Luk case where they split the core and did different analyses on the different halves or that other case where they had different LOI/BD sample volumes for higher and lower depth increments.

**Comment by jaxinewolfe** [comment]
We will be reinstating the testConditional() fxn in hook script QAQC. I've performed an initial sweep of the synthesis to compile a table which lists [missing conditional attributes](https://github.com/Smithsonian/CCRCN-Data-Library/blob/main/data/QA/missing_conditional_attributes.csv) for each study. These hook scripts will be revisited for revisions (if possible/necessary).

**Comment by jaxinewolfe** [comment]
@BettsH @cheneyr Just putting this issue on your radar! Solidifying our standards, QAQC tests, and introducing a new database version last year led to revisiting all the hook scripts. This is where we've been tracking those revisions and documenting things to address in the future that will make this synthesis even more solid. For example, there are some studies that don't have methods tables yet, which is probably one of the top things I'd like to address (esp. since we want to create a workflow eventually which derives carbon stock etc. reliably from these data). I'm thinking we can do a hackathon in the near future to work through a bunch of these.

**Comment by jaxinewolfe** [comment]
Small hook script fixes and questions

- [ ] Boyd et al 2017: unexplained empty rows with some data but no associated depth interval
- [ ] Lagomasino 2020: has one negative DBD value (present in original data as well)
- [ ] remove any modeled C values
- [ ] impacts: Breithaupt 2017, Poppe 2019, and CRMS database
