### ISSUE TITLE
Hook: Marot et al 2022

### ISSUE THREAD

**Issue by jaxinewolfe** [Smithsonian/CCN-Data-Library#69]
- [x] complete data curation
- [x] QAQC
- [x] managers review

**Comment by jaxinewolfe** [comment]
Hey @BettsH! I took another look at these files and worked out a way to automate the data table merging for soil properties and the dating info (except radiocarbon, which we should just read in and merge manual from the two excel files). I was also able to merge the information from the FieldLog tables. There also aren't any Field Logs for sites 2016-348-FA (16CCT04) and 2016-358-FA (16CCT07), but maybe this info will need to be found in their XML files. Hopefully the only manual work you'll have to do is fill out the methods table.

The script is in the Marot folder, I didn't output any of the tables that are created because they still need some work and it wouldn't make sense to output a half-baked table just to read it in again. But it's better to clean up a merged table than clean up each one individually. So! Go ahead and run the script and see where the curation can be taken from there. If you worked on this today, you will likely be able to apply any code you developed to the curation of these merged products. 

One thing: there are cases where the column names were slightly different from one another and so they created separate columns when I joined the table rows. Since there won't be an overlap in values between these two columns, you can merge them into one column using the function coalesce() within mutate. Ex. ...mutate(new_col = coalesce(col1, col2)) and drop the old incomplete cols. Don't bother merging columns that we won't need for the final tables though.

Happy curating! 🤓

**Comment by BettsH** [comment]
@jaxinewolfe I resolved the method IDs to reflect each of the coring methods with "shovel corer" as one of the types (even though this is not an option under coring_method in the library data structure Methods table). Another thing to note is that there are several occurrences of cores sharing the same lat/long: this is OK because the data sheets reflect this apparent duplication.

@HolmquistJ I seem to have answered all of the questions that I sent to you in my last update email regarding this hook, so no need to go back to that email.

**Comment by jaxinewolfe** [comment]
@BettsH That sounds good to me. Yes, the coordinate duplication is not uncommon, especially in cases where people take "replicate" cores. Thanks for all your work on this, it's not an easy hook by any means! Let me know when you've gotten to a point where you'd like me to look over the curation script.

@HolmquistJ _shovel cores_ and _surface samples_ are infrequent, but they do occur so we might consider adopting them into the controlled vocab for coring method. Perhaps in the new year, we can take some time to revisit our approach to uncontrolled vocabulary in the Library ([documented here](https://github.com/Smithsonian/CCRCN-Data-Library/blob/main/docs/resolve_uncontrolled.csv)).

**Comment by HolmquistJ** [comment]
There is one issue I can see with the Ward 2021 data. There are bad longitudes for cores around Elkhorn Slough. 

<img width="565" alt="Screen Shot 2023-11-20 at 10 13 45 PM" src="https://github.com/Smithsonian/CCN-Data-Library/assets/15948972/9b6d13d5-3db9-4a2b-a87a-abbc165b486f">

**Comment by HolmquistJ** [comment]
@BettsH There was an issue with this hook. Rose made an edit that caused all cores to be classified as marshes. I reverted back to Henrey's original version.
