### ISSUE TITLE
Data Hook: Piazza et al. 

### ISSUE THREAD

**Issue by HolmquistJ** [Smithsonian/CCN-Data-Library#87]
The Piazza data is still associated with the Holmquist 2018 hook script despite having its own synthesis. The Piazza data needs to be removed from the Holmquist 2018 hook and needs to be given its own.

**Comment by jaxinewolfe** [comment]
Thanks for flagging this @HolmquistJ I recall there was some issue with a mismatch of core IDs between two tables that made us decide to leave the 2018 version in there at the time, but I agree that this should be resolved. I'll look into swapping things out for the next update.
