### ISSUE TITLE
Need to manually fix 'fill series' error in Ward 2021

### ISSUE THREAD

**Issue by HolmquistJ** [Smithsonian/CCN-Data-Library#97]
These depth increments for Tomales Bay and Elkhorn slough have auto fill errors. This is causing each depth increment with unique lat-long's to be read in as a separate core. We need to create a manually edited version without the autofill errors and re-run the hook script with the corrected file. In the meantime we should also alert the authors to the error in case they want to submit a correction to their original data release.

<img width="530" alt="Screen Shot 2023-11-21 at 9 18 46 AM" src="https://github.com/Smithsonian/CCN-Data-Library/assets/15948972/8c5161ee-68f7-491f-9d06-491cced7107f">
<img width="383" alt="Screen Shot 2023-11-21 at 9 19 50 AM" src="https://github.com/Smithsonian/CCN-Data-Library/assets/15948972/63ace3e5-c6fd-4b6f-8b8c-26233f45d8b3">

**Comment by cheneyr** [comment]
The fill series error is fixed and I'll reach out to the authors and let them know this afternoon.
